### ISSUE TITLE
Issue with first mediafire link

### ISSUE THREAD

**Issue by PetarOlujic** [nejcpirecnik/Chrome-Artemis#1]
Hello,
I wanted to address the issue that you commented in your readme.txt file. MediaFire is blocking your download link "https://download1498.mediafire.com/jbon2l88ucyg/7w31zqu1rpcw6xf/pw.exe". Sending a screenshot:
![image](https://user-images.githubusercontent.com/48801528/104030383-9b42f680-51cb-11eb-80b1-f95470a37866.png)

The following problem gives me this error, I believe it is related to the first screenshot. Here is the error itself in powershell:
![image](https://user-images.githubusercontent.com/48801528/104031210-bbbf8080-51cc-11eb-8854-53b06c2433df.png)

Is there possibly another page that would not block your content? 

EDIT: Cutting the main powershell screenshot into two pieces so you can see more clearly: 
![image](https://user-images.githubusercontent.com/48801528/104031472-0e00a180-51cd-11eb-915f-8e4ef3421d7a.png)
![image](https://user-images.githubusercontent.com/48801528/104031592-2f618d80-51cd-11eb-9b5f-52c90016d1e2.png)

**Comment by nejcpirecnik** [comment]
Hey!
Thank you!
I'll try to find a solution tomorrow.
Dropbox might work...

Will send a working link :)

Cheers.

**Comment by StroopKoekje** [comment]
the links he need to download from mediafire are blocked, can you post the files so i can upload it to my own web server?

**Comment by nejcpirecnik** [comment]
The files have been updated! Give them a try :) If it doesn't work, let me know!

**Comment by PetarOlujic** [comment]
Hello again,
I tried to run again, and got this kind of error. I am not able to access the source code to check the errors itself (not familiar with the language you used, or editor I could open it with). It is possible that it will not run because I am using mousejack from Bastille for this matter, and a CrazyRadio USB dongle, and not original ducky encoded USB drive.
Here is the screenshot of the given error:
![image](https://user-images.githubusercontent.com/48801528/104311293-43f79b80-54d5-11eb-9b75-b803f0872514.png)

![image](https://user-images.githubusercontent.com/48801528/104311307-4954e600-54d5-11eb-846d-d9546690b734.png)

Thanks in advance.

**Comment by nejcpirecnik** [comment]
The problem for you seems to be in the chrome.ps1.
The script was also written in a programming language called "Ducky Script", which is made only for the actual Rubber Ducky.
You could try modifying the code to suit your needs.

I've provided the .ps1 file, try to edit that.

Let me know if it works.
Kind regards.
